// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVcYiFZRA7PuTF4kly3jPPm9ZuXSSjCl0',
    appId: '1:397905096023:web:877515205602e536032212',
    messagingSenderId: '397905096023',
    projectId: 'shopping-429dd',
    authDomain: 'shopping-429dd.firebaseapp.com',
    storageBucket: 'shopping-429dd.appspot.com',
    measurementId: 'G-BSW9RC49ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ZvRfuOCiH4Oly8PbNIBW8Uc7Kh8asLc',
    appId: '1:397905096023:android:b5bcbb86ccc420cd032212',
    messagingSenderId: '397905096023',
    projectId: 'shopping-429dd',
    storageBucket: 'shopping-429dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaRqn5PB1Na-ydMvusxXsL0xgM_jZ_NaM',
    appId: '1:397905096023:ios:31bad0f3d7e60ba0032212',
    messagingSenderId: '397905096023',
    projectId: 'shopping-429dd',
    storageBucket: 'shopping-429dd.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaRqn5PB1Na-ydMvusxXsL0xgM_jZ_NaM',
    appId: '1:397905096023:ios:90457ce7ac610b26032212',
    messagingSenderId: '397905096023',
    projectId: 'shopping-429dd',
    storageBucket: 'shopping-429dd.appspot.com',
    iosBundleId: 'com.example.task.RunnerTests',
  );
}
